name: cv_send
description: "I'll tell you a little about me."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '3.8.1'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_modular: ^6.4.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.0
  intl: ^0.20.0
  dio: ^5.8.0
  dio_smart_retry: ^7.0.1
  dio_cache_interceptor: ^4.0.3
  equatable: ^2.0.7
  flutter_svg: ^2.2.0
  dart_ipify: ^1.1.1
  lottie: ^3.3.1
  shimmer_animation: ^2.2.2
  url_launcher: ^6.3.2
  timelines: ^0.1.0
  animations: ^2.0.11
  gif: ^2.3.0
  gif_view: ^1.0.3
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/animations/loading/
  - assets/images/
  - assets/gif/
  - assets/svg/